name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn test
    - name: Build the Docker image
      run: |
        docker build -t kostanproff/fullstack-typescript-mern-todo ./client
        docker build -t kostanproff/fullstack-typescript-mern-todo ./server       
        
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       context: .
       file: ./Dockerfile
       push: true
       repository: kostanproff/webnext
       tags: latest, ${{ github.run_number }}
